name: Build Project

on: [push, pull_request]

jobs:
  Clang-Format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: clang format
      run: clang-format -style=file -Werror src/*
  Clang-Tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: clang tidy
      run: clang-tidy --quiet --format-style=file src/* -- -x c++
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
